services:
  ebi:
    build:
      context: ./app/ebi
    container_name: ebi-ingest
    mem_limit: 4g
    cpus: 0.75
    restart: "no"
    volumes:
      - ./app/ebi:/app


  epfl:
    build:
      context: ./app/epfl
    container_name: epfl-ingest
    mem_limit: 4g
    cpus: 0.75
    restart: "no"
    volumes:
      - ./app/epfl:/app


  flyem:
    build:
      context: ./app/flyem
    container_name: flyem-ingest
    mem_limit: 4g
    cpus: 0.75
    restart: "no"
    volumes:
      - ./app/flyem:/app


  idr:
    build:
      context: ./app/idr
    container_name: idr-ingest
    mem_limit: 4g
    cpus: 0.75
    restart: "no"
    volumes:
      - ./app/idr:/app


  openorganelle:
    build:
      context: ./app/openorganelle
    container_name: openorganelle-ingest
    mem_limit: 4g
    cpus: 0.75
    restart: "no"
    volumes:
      - ./app/openorganelle:/app
